// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB6ECPyMifl0eXsZo35kdefL7TvSn870g',
    appId: '1:638900177465:web:330686fff4c7a72d149be8',
    messagingSenderId: '638900177465',
    projectId: 'app-dev-51b70',
    authDomain: 'app-dev-51b70.firebaseapp.com',
    storageBucket: 'app-dev-51b70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG9n6JCE2mbGEeEx-P0SRwxz0J0jFkwpc',
    appId: '1:638900177465:android:879bba0a081eb12d149be8',
    messagingSenderId: '638900177465',
    projectId: 'app-dev-51b70',
    storageBucket: 'app-dev-51b70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJpDrJaqGF4aqeukRU_rcfjrGF3qhIRAA',
    appId: '1:638900177465:ios:cb7dd5c148d7bd18149be8',
    messagingSenderId: '638900177465',
    projectId: 'app-dev-51b70',
    storageBucket: 'app-dev-51b70.firebasestorage.app',
    iosBundleId: 'com.example.appdev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB6ECPyMifl0eXsZo35kdefL7TvSn870g',
    appId: '1:638900177465:web:ea8eaf4ff8bf99ba149be8',
    messagingSenderId: '638900177465',
    projectId: 'app-dev-51b70',
    authDomain: 'app-dev-51b70.firebaseapp.com',
    storageBucket: 'app-dev-51b70.firebasestorage.app',
  );
}
